// Generated by CoffeeScript 1.4.0
(function() {

  define(function() {
    var ManyToOne;
    return ManyToOne = (function() {

      function ManyToOne() {}

      ManyToOne.prototype.addToJson = function(json) {
        return json[this.name] = {
          id: this.value.get("id")
        };
      };

      ManyToOne.prototype.setFromJson = function(json, clean) {
        this.isDirty = !clean;
        return this.value.update(json);
      };

      ManyToOne.prototype.getProperty = function(name) {
        return this.value.getProperty(name);
      };

      return ManyToOne;

    })();
  });

}).call(this);
