// Generated by CoffeeScript 1.4.0
(function() {

  define(["underscore"], function(_) {
    var OneToMany;
    return OneToMany = (function() {

      function OneToMany(value) {
        this.value = value != null ? value : [];
      }

      OneToMany.prototype.addToJson = function(json) {
        var model;
        return json[this.name] = (function() {
          var _i, _len, _ref, _results;
          _ref = this.value;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            model = _ref[_i];
            _results.push(model.asJson());
          }
          return _results;
        }).call(this);
      };

      OneToMany.prototype.add = function(value) {
        return this.value.push(value);
      };

      OneToMany.prototype.removeAll = function() {
        return this.value.length = 0;
      };

      OneToMany.prototype.setFromJson = function(json, clean) {
        var pair, _i, _len, _ref, _results;
        this.isDirty = !clean;
        _ref = _.zip(this.value, json);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pair = _ref[_i];
          _results.push(pair[0].update(pair[1], clean));
        }
        return _results;
      };

      return OneToMany;

    })();
  });

}).call(this);
