// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["ViewFirstModel", "BindHelpers", "OneToMany", "ManyToOne"], function(ViewFirstModel, BindHelpers, OneToMany, ManyToOne) {
    var ViewFirst;
    return ViewFirst = (function(_super) {

      __extends(ViewFirst, _super);

      function ViewFirst() {
        return ViewFirst.__super__.constructor.apply(this, arguments);
      }

      ViewFirst.Model = ViewFirstModel;

      ViewFirst.OneToMany = OneToMany;

      ViewFirst.ManyToOne = ManyToOne;

      return ViewFirst;

    })(BindHelpers);
  });

}).call(this);
