// Generated by CoffeeScript 1.4.0
(function() {
  var __slice = [].slice;

  define(function() {
    var ViewFirstEvents;
    return ViewFirstEvents = (function() {
      var getFuncsObjectForEvent, getNextId;

      ViewFirstEvents.prototype.lastIdUsed = 0;

      function ViewFirstEvents() {
        this.events = {};
      }

      getNextId = function() {
        return this.lastIdUsed = this.lastIdUsed + 1;
      };

      getFuncsObjectForEvent = function(eventName) {
        if (this.events[eventName] == null) {
          this.events[eventName] = {};
        }
        return this.events[eventName];
      };

      ViewFirstEvents.prototype.on = function(eventName, func) {
        var funcs, id;
        id = getNextId.call(this);
        funcs = getFuncsObjectForEvent.call(this, eventName);
        funcs[id] = func;
        return {
          off: function() {
            return delete funcs[id];
          }
        };
      };

      ViewFirstEvents.prototype.trigger = function() {
        var eventName, func, funcs, key, other, _results;
        eventName = arguments[0], other = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        funcs = getFuncsObjectForEvent.call(this, eventName);
        _results = [];
        for (key in funcs) {
          func = funcs[key];
          _results.push(func.apply(this, other));
        }
        return _results;
      };

      return ViewFirstEvents;

    })();
  });

}).call(this);
